/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-radio_telescope_ENAC
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_RADIO_TELESCOPE_ENAC_API_H
#define INCLUDED_RADIO_TELESCOPE_ENAC_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_radio_telescope_ENAC_EXPORTS
#define RADIO_TELESCOPE_ENAC_API __GR_ATTR_EXPORT
#else
#define RADIO_TELESCOPE_ENAC_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_RADIO_TELESCOPE_ENAC_API_H */
